url: https://y7kim.github.io
baseurl: http://localhost:3000/
dev: true

# Site settings
title: 台大合唱團
email: b03902074@ntu.edu.tw
description: "台大合唱團是台灣大學學生合唱團，由眾多年輕的合唱愛好者所組成。團員具有優秀的領悟力及可塑性，並且對於音樂充滿高度的熱忱；不僅勇於嘗試各種曲目，演出形式更力求創新，搭配舞台燈光與肢體動作設計，帶給觀眾更豐富的視聽感受。"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333
  ternary: fff

social:
  facebook: https://zh-tw.facebook.com/NTUChorus
  youtube: https://www.youtube.com/user/NTUChorus
  google_plus: https://plus.google.com/113145450167726197942/posts

# Build settings
markdown: kramdown
permalink: pretty
exclude: [_posts,vendor,Gemfile*,node_modules,package.json,gulpfile.js,bin,vendor,config.rb,production.sh]
port: 4444
